# `BERCHMANS KEVIN S`

# `Sentiment Analysis on Movie Reviews`

###  Exercise - 1

In [1]:
import pandas as pd

In [2]:
file = pd.read_csv('train.tsv', sep='\t')

In [3]:
file

,PhraseId,SentenceId,Phrase,Sentiment
0,1,1,A series of escapades demonstrating the adage ...,1
1,2,1,A series of escapades demonstrating the adage ...,2
2,3,1,A series,2
3,4,1,A,2
4,5,1,series,2
5,6,1,of escapades demonstrating the adage that what...,2
6,7,1,of,2
7,8,1,escapades demonstrating the adage that what is...,2
8,9,1,escapades,2
9,10,1,demonstrating the adage that what is good for ...,2
10,11,1,demonstrating the adage,2
11,12,1,demonstrating,2
12,13,1,the adage,2
13,14,1,the,2
14,15,1,adage,2
15,16,1,that what is good for the goose,2
16,17,1,that,2
17,18,1,what is good for the goose,2
18,19,1,what,2
19,20,1,is good for the goose,2
20,21,1,is,2
21,22,1,good for the goose,3
22,23,1,good,3
23,24,1,for the goose,2
24,25,1,for,2
25,26,1,the goose,2
26,27,1,goose,2
27,28,1,"is also good for the gander , some of which oc...",2
28,29,1,"is also good for the gander , some of which oc...",2
29,30,1,is also,2
...,...,...,...,...
156030,156031,8542,a joke in the United States,2
156031,156032,8543,The movie 's downfall is to substitute plot fo...,1
156032,156033,8543,The movie 's downfall,1
156033,156034,8543,is to substitute plot for personality .,1
156034,156035,8543,is to substitute plot for personality,1
156035,156036,8543,to substitute plot for personality,2
156036,156037,8543,substitute plot for personality,1
156037,156038,8543,substitute plot,2
156038,156039,8543,for personality,2
156039,156040,8544,"The film is darkly atmospheric , with Herrmann...",2
156040,156041,8544,"is darkly atmospheric , with Herrmann quietly ...",2
156041,156042,8544,"is darkly atmospheric , with Herrmann quietly ...",2
156042,156043,8544,"is darkly atmospheric ,",2
156043,156044,8544,is darkly atmospheric,3
156044,156045,8544,with Herrmann quietly suggesting the sadness a...,2
156045,156046,8544,Herrmann quietly suggesting the sadness and ob...,2
156046,156047,8544,Herrmann,2
156047,156048,8544,quietly suggesting the sadness and obsession b...,1
156048,156049,8544,suggesting the sadness and obsession beneath H...,2
156049,156050,8544,suggesting the sadness and obsession,2
156050,156051,8544,the sadness and obsession,2
156051,156052,8544,sadness and obsession,1
156052,156053,8544,sadness and,1
156053,156054,8544,beneath Hearst 's forced avuncular chortles,2
156054,156055,8544,Hearst 's forced avuncular chortles,2
156055,156056,8544,Hearst 's,2
156056,156057,8544,forced avuncular chortles,1
156057,156058,8544,avuncular chortles,3
156058,156059,8544,avuncular,2
156059,156060,8544,chortles,2

In [4]:
file.head()

,PhraseId,SentenceId,Phrase,Sentiment
0,1,1,A series of escapades demonstrating the adage ...,1
1,2,1,A series of escapades demonstrating the adage ...,2
2,3,1,A series,2
3,4,1,A,2
4,5,1,series,2

In [5]:
file.shape

(156060, 4)

In [6]:
file.size

624240

In [7]:
file.describe()

            PhraseId     SentenceId      Sentiment
count  156060.000000  156060.000000  156060.000000
mean    78030.500000    4079.732744       2.063578
std     45050.785842    2502.764394       0.893832
min         1.000000       1.000000       0.000000
25%     39015.750000    1861.750000       2.000000
50%     78030.500000    4017.000000       2.000000
75%    117045.250000    6244.000000       3.000000
max    156060.000000    8544.000000       4.000000

In [8]:
file.columns

Index(['PhraseId', 'SentenceId', 'Phrase', 'Sentiment'], dtype='object')

In [9]:
file.tail()

        PhraseId  SentenceId                     Phrase  Sentiment
156055    156056        8544                  Hearst 's          2
156056    156057        8544  forced avuncular chortles          1
156057    156058        8544         avuncular chortles          3
156058    156059        8544                  avuncular          2
156059    156060        8544                   chortles          2

In [10]:
file['Sentiment'].value_counts()

2    79582
3    32927
1    27273
4     9206
0     7072
Name: Sentiment, dtype: int64

###  Exercise - 2

In [11]:
a1 = file.loc[file.Sentiment == 0]
b1 = file.loc[file.Sentiment == 1]
c1 = file.loc[file.Sentiment == 2]
d1 = file.loc[file.Sentiment == 3]
e1 = file.loc[file.Sentiment == 4]

In [12]:
small_rotten_train = pd.concat([a1[:200], b1[:200], c1[:200], d1[:200], e1[:200]])

### Exercise - 3

In [13]:
small_rotten_train

,PhraseId,SentenceId,Phrase,Sentiment
101,102,3,would have a hard time sitting through this one,0
103,104,3,have a hard time sitting through this one,0
157,158,5,Aggressive self-glorification and a manipulati...,0
159,160,5,self-glorification and a manipulative whitewash,0
201,202,7,Trouble Every Day is a plodding mess .,0
208,209,7,is a plodding mess,0
210,211,7,plodding mess,0
261,262,10,could hate it for the same reason,0
264,265,10,hate it,0
265,266,10,hate,0
311,312,12,is Oedekerk 's realization of his childhood dr...,0
430,431,16,baseball movies that try too hard to be mythic,0
848,849,32,"Hampered -- no , paralyzed -- by a self-indulg...",0
861,862,32,a self-indulgent script,0
919,920,34,There 's very little sense to what 's going on...,0
1001,1002,36,avoid,0
1003,1004,37,almost feels as if the movie is more intereste...,0
1023,1024,38,The movie 's progression into rambling incoher...,0
1024,1025,38,The movie 's progression into rambling incoher...,0
1032,1033,38,gives new meaning to the phrase ` fatal script...,0
1044,1045,38,` fatal script error,0
1046,1047,38,fatal script error,0
1099,1100,41,Tartakovsky 's team has some freakish powers o...,0
1131,1132,41,of narrative banality,0
1158,1159,42,bad,0
1282,1283,48,"'m sure the filmmaker would disagree , but , h...",0
1295,1296,48,"honestly , I do n't see the point",0
1372,1373,51,clunky TV-movie approach,0
1445,1446,53,"Thanks largely to Williams , all the interesti...",0
1468,1469,53,the rest is just an overexposed waste of film,0
...,...,...,...,...
3322,3323,125,honest,4
3334,3335,125,"pat storylines , precious circumstances and be...",4
3344,3345,125,beautiful,4
3356,3357,126,"it 's still a sweet , even delectable diversion .",4
3358,3359,126,"'s still a sweet , even delectable diversion",4
3362,3363,126,"sweet , even delectable",4
3365,3366,126,delectable,4
3367,3368,127,A thoughtful and surprisingly affecting portra...,4
3368,3369,127,A thoughtful and surprisingly affecting portra...,4
3373,3374,127,thoughtful and surprisingly affecting,4
3391,3392,127,powerful,4
3474,3475,129,brilliant,4
3492,3493,130,"A triumph , a film that hews out a world and c...",4
3493,3494,130,"A triumph , a film that hews out a world and c...",4
3495,3496,130,A triumph,4
3497,3498,130,a film that hews out a world and carries us ef...,4
3529,3530,132,"A fascinating , dark thriller that keeps you",4
3629,3630,136,One of the year 's most weirdly engaging and u...,4
3642,3643,137,Intriguing and downright intoxicating .,4
3643,3644,137,Intriguing and downright intoxicating,4
3646,3647,137,downright intoxicating,4
3671,3672,138,fresh,4
3708,3709,140,Sleek and arty,4
3737,3738,142,'s face is -RRB- an amazing slapstick instrument,4
3743,3744,142,an amazing slapstick,4
3744,3745,142,amazing slapstick,4
3745,3746,142,amazing,4
3847,3848,147,When cowering and begging at the feet a scruff...,4
3866,3867,147,gives her best performance since Abel Ferrara ...,4
3993,3994,151,Spielberg 's realization of a near-future Amer...,4

In [14]:
X = small_rotten_train.Phrase
X

101       would have a hard time sitting through this one
103             have a hard time sitting through this one
157     Aggressive self-glorification and a manipulati...
159       self-glorification and a manipulative whitewash
201                Trouble Every Day is a plodding mess .
208                                    is a plodding mess
210                                         plodding mess
261                     could hate it for the same reason
264                                               hate it
265                                                  hate
311     is Oedekerk 's realization of his childhood dr...
430        baseball movies that try too hard to be mythic
848     Hampered -- no , paralyzed -- by a self-indulg...
861                               a self-indulgent script
919     There 's very little sense to what 's going on...
1001                                                avoid
1003    almost feels as if the movie is more intereste...
1023    The movie 's progression into rambling incoher...
1024    The movie 's progression into rambling incoher...
1032    gives new meaning to the phrase ` fatal script...
1044                                 ` fatal script error
1046                                   fatal script error
1099    Tartakovsky 's team has some freakish powers o...
1131                                of narrative banality
1158                                                  bad
1282    'm sure the filmmaker would disagree , but , h...
1295                    honestly , I do n't see the point
1372                             clunky TV-movie approach
1445    Thanks largely to Williams , all the interesti...
1468        the rest is just an overexposed waste of film
                              ...
3322                                               honest
3334    pat storylines , precious circumstances and be...
3344                                            beautiful
3356    it 's still a sweet , even delectable diversion .
3358         's still a sweet , even delectable diversion
3362                              sweet , even delectable
3365                                           delectable
3367    A thoughtful and surprisingly affecting portra...
3368    A thoughtful and surprisingly affecting portra...
3373                thoughtful and surprisingly affecting
3391                                             powerful
3474                                            brilliant
3492    A triumph , a film that hews out a world and c...
3493    A triumph , a film that hews out a world and c...
3495                                            A triumph
3497    a film that hews out a world and carries us ef...
3529         A fascinating , dark thriller that keeps you
3629    One of the year 's most weirdly engaging and u...
3642              Intriguing and downright intoxicating .
3643                Intriguing and downright intoxicating
3646                               downright intoxicating
3671                                                fresh
3708                                       Sleek and arty
3737     's face is -RRB- an amazing slapstick instrument
3743                                 an amazing slapstick
3744                                    amazing slapstick
3745                                              amazing
3847    When cowering and begging at the feet a scruff...
3866    gives her best performance since Abel Ferrara ...
3993    Spielberg 's realization of a near-future Amer...
Name: Phrase, Length: 1000, dtype: object

In [15]:
y = small_rotten_train.Sentiment
y

101     0
103     0
157     0
159     0
201     0
208     0
210     0
261     0
264     0
265     0
311     0
430     0
848     0
861     0
919     0
1001    0
1003    0
1023    0
1024    0
1032    0
1044    0
1046    0
1099    0
1131    0
1158    0
1282    0
1295    0
1372    0
1445    0
1468    0
       ..
3322    4
3334    4
3344    4
3356    4
3358    4
3362    4
3365    4
3367    4
3368    4
3373    4
3391    4
3474    4
3492    4
3493    4
3495    4
3497    4
3529    4
3629    4
3642    4
3643    4
3646    4
3671    4
3708    4
3737    4
3743    4
3744    4
3745    4
3847    4
3866    4
3993    4
Name: Sentiment, Length: 1000, dtype: int64

In [16]:
import nltk
from nltk.corpus import stopwords
nltk.download('stopwords')
stop_words = set(stopwords.words('english'))

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\1mscdsa07\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

In [17]:
from nltk.stem import WordNetLemmatizer
import nltk
nltk.download('wordnet')

[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\1mscdsa07\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!

True

In [18]:
Lemmatizer = WordNetLemmatizer()

In [19]:
def clean_reviews(review):
    tokens = review.lower().split()
    filtered_tokens = [
        Lemmatizer.lemmatize(w) for w in tokens if w not in stop_words
    ]
    return" ".join(filtered_tokens)

In [20]:
temp = X.tolist()
fax = []

In [21]:
for i in temp:
    fax.append(clean_reviews(i))    
n_X = pd.Series(fax)

In [22]:
from sklearn.model_selection import train_test_split
X_train, y_train, X_test, y_test = train_test_split(n_X, y, test_size=0.20)

In [23]:
from sklearn.feature_extraction.text import TfidfVectorizer

tf = TfidfVectorizer(min_df=3, max_features=None,
                    ngram_range=(1,2), use_idf=1)
tf

TfidfVectorizer(analyzer='word', binary=False, decode_error='strict',
        dtype=<class 'numpy.int64'>, encoding='utf-8', input='content',
        lowercase=True, max_df=1.0, max_features=None, min_df=3,
        ngram_range=(1, 2), norm='l2', preprocessor=None, smooth_idf=True,
        stop_words=None, strip_accents=None, sublinear_tf=False,
        token_pattern='(?u)\\b\\w\\w+\\b', tokenizer=None, use_idf=1,
        vocabulary=None)

In [24]:
tf.fit_transform(X_train)

<800x861 sparse matrix of type '<class 'numpy.float64'>'
	with 4731 stored elements in Compressed Sparse Row format>

In [25]:
from sklearn.naive_bayes import MultinomialNB

In [26]:
clf = MultinomialNB()

In [27]:
X_train

837                                              amusing
523                                      title character
652    still like moonlight mile , better judgment da...
842    work spectacularly well ... shiver-inducing , ...
673               like le dizzily gorgeous companion mr.
40     downright transparent script 's endless assaul...
588                                               source
517
718            term 's inoffensive actually rather sweet
301                                      run-of-the-mill
447                                               amount
109                                       bad bluescreen
819                                          extravagant
18             movie 's progression rambling incoherence
589                                             kung pow
859    grace call prevention rather place blame , mak...
493                                          ethnography
91     dupe viewer taking important simply movie ugly...
65     crass , contrived sequel fails , make second-g...
345              movie interested entertaining amusing u
828                                                 love
48                                   directed , barely ,
996                                              amazing
827                                         love -- much
427                                                 also
905                                                 sexy
186    film bad n't improve upon experience staring b...
236                                                  n't
791                                         experimental
940                  visually masterful work quiet power
                             ...
503                                shakespearean tragedy
857    bloody sunday grace call prevention rather pla...
487                                                  one
870       perhaps 's cliche call film ` refreshing , ' .
945                                          masterpiece
378                                                -lrb-
936    return narrative filmmaking visually masterful...
883          smart , provocative drama nearly impossible
816                                       absolute joy .
689    case study exists apart movie 's political ram...
415
496                  intrigue , betrayal , deceit murder
762                                                 team
763                          freakish power visual charm
433                                                    ,
319                                little sense 's going
469                                   ismail merchant 's
559                                             familiar
191    's difficult imagine confused , le interesting...
928                   surprisingly ` solid ' achievement
977    thoughtful surprisingly affecting portrait scr...
722                                         rather sweet
643                                         absolute joy
685                                           indie year
963                            better summer blockbuster
128                                                 dull
485                                                  one
6                                          plodding mess
534                                                  day
624                                               rooted
Length: 800, dtype: object

In [28]:
# clf.fit(X_train, y_train)

In [29]:
y_train

830                                                 best
439           occasionally amuses none amount much story
806                                            thrilling
942                              visually masterful work
639                                                  pow
615                                             intrigue
138    filmmaking plainly dull visually ugly n't inco...
452                                                story
216                                               murder
904                                      inventive , fun
167    superfluous sequel ... plagued old familiar fe...
8                                                   hate
670                                    bilingual charmer
39     generic villain lack intrigue -lrb- funny acce...
617                                     juicy soap opera
944                                            masterful
71                                                 fails
450                                           much story
880    smart , provocative drama nearly impossible : ...
507                                                opera
646    something serious say way extravagant chance d...
608                                      worth seeking .
628    earnest , thick wit play like reading bartlett...
302    hampered -- , paralyzed -- self-indulgent scri...
981                                            brilliant
893                                      heartfelt story
635                                 source high hilarity
95                           ugly look hollywood product
793    tricky satisfying david mamet 's airless cinem...
510                                         manipulative
                             ...
900    pretty good execution story 's lot richer one ...
9                                                   hate
972                                            beautiful
119            , wear welcome tryingly title character .
446                                    amount much story
845                                   spectacularly well
975                              sweet , even delectable
691    occurs 7 time windtalker good indication serio...
711                                         wilde 's wit
917                            's wonderful big screen .
638                                             hilarity
811                                  sincere performance
659                sweet modest ultimately winning story
818                                                  joy
741                                         entertaining
23                                    narrative banality
61     `` analyze '' one crass , contrived sequel fai...
846                                        spectacularly
834    first computer-generated feature cartoon feel ...
705                   offer opportunity occasional smile
292    give u reason theater beyond wilde 's wit acto...
704                                   importance earnest
760    tartakovsky 's team freakish power visual charm ,
144                   corny dialogue preposterous moment
207                                hard time sitting one
528                                              midlife
530                                          narratively
848                               sensational true-crime
522                                      title character
755                          could young romantic date .
Length: 200, dtype: object